#!/usr/bin/env python3
"""Generate plugins/karakam/agents/*.md from tools/agents-src/*.md.

Claude Code sets a sub-agent's effort only from its definition's frontmatter —
the Agent tool can't pass one per call — so each effort level Karagöz needs is
its own agent file. Their bodies must stay identical; this script is the single
source. Run it after editing anything in tools/agents-src/, and use
`--check` in CI / before committing to catch hand-edited drift.

  python3 tools/build_agents.py          # write
  python3 tools/build_agents.py --check  # exit 1 if agents/ is stale
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "tools" / "agents-src"
OUT = ROOT / "plugins" / "karakam" / "agents"

ONLY = ("Used only by the karakam {skill} skill, which spawns it by name; "
        "don't delegate other work to it.")

VARIANTS = [
    # name, source, effort, tools, description
    *[(f"worker-{e}", "worker", e, "Read, Write, Edit, Glob, Grep, Bash",
       f"Karagöz Worker at {e} effort: carries out one plan step test-first "
       "inside its files_touched and writes a short log. " + ONLY.format(skill="karagoz"))
      for e in ("low", "medium", "high", "xhigh")],
    *[(f"observer-{e}", "observer", e, "Read, Glob, Grep, Bash, Write",
       f"Karagöz Observer at {e} effort: adversarially audits one finished plan "
       "step by running its checks itself, and returns PASS or FAIL with evidence. "
       + ONLY.format(skill="karagoz"))
      for e in ("medium", "high")],
    ("critic", "critic", "medium", "Read, Glob, Grep",
     "Hacivat plan critic: reviews a plan on disk through one named lens and "
     "returns severity-tagged objections plus a 0-10 score. " + ONLY.format(skill="hacivat")),
]


def render(name, src, effort, tools, description):
    body = (SRC / f"{src}.md").read_text(encoding="utf-8")
    return (f"---\nname: {name}\ndescription: {description}\nmodel: opus\n"
            f"effort: {effort}\ntools: {tools}\n---\n\n"
            "<!-- Generated by tools/build_agents.py from tools/agents-src/"
            f"{src}.md — edit the source, not this file. -->\n\n{body}")


def main():
    check = "--check" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    wanted = {f"{v[0]}.md": render(*v) for v in VARIANTS}
    stale = [n for n, text in wanted.items()
             if not (OUT / n).exists() or (OUT / n).read_text(encoding="utf-8") != text]
    extra = [p.name for p in OUT.glob("*.md") if p.name not in wanted]
    if check:
        for n in stale + extra:
            print(f"stale: agents/{n}")
        sys.exit(1 if stale or extra else 0)
    for n in stale:
        (OUT / n).write_text(wanted[n], encoding="utf-8")
    for n in extra:
        (OUT / n).unlink()
    print(f"agents: {len(wanted)} ({len(stale)} written, {len(extra)} removed)")


if __name__ == "__main__":
    main()
