#!/usr/bin/env python3
"""Generate plugins/karakam/agents/*.md from tools/agents-src/*.md.

Claude Code sets a sub-agent's effort only from its definition's frontmatter —
the Agent tool can't pass one per call — so each effort level Karagöz needs is
its own agent file (and so is each model a Worker can run on). Their bodies must stay identical; this script is the single
source. Run it after editing anything in tools/agents-src/, and use
`--check` in CI / before committing to catch hand-edited drift.

  python3 tools/build_agents.py          # write
  python3 tools/build_agents.py --check  # exit 1 if agents/ is stale
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "tools" / "agents-src"
OUT = ROOT / "plugins" / "karakam" / "agents"

ONLY = ("Used only by the karakam {skill} skill, which spawns it by name; "
        "don't delegate other work to it.")

# Workers and Observers inherit the session's tools — MCP servers included, so a
# step can work on a Drive or a database the user connected — minus the ones that
# would let a sub-agent run the loop itself. An allow-list (`tools:`) would cut
# every MCP tool off. Critics only read the plan, so they keep an allow-list.
DENY = "Agent, Task, Skill, CronCreate, CronDelete, ScheduleWakeup, EnterWorktree, ExitWorktree"

VARIANTS = [
    # name, source, model, effort, tools ("deny" → inherit minus DENY), description
    *[(f"worker-{e}", "worker", "sonnet", e, "deny",
       f"Karagöz Worker (Sonnet, {e} effort): carries out one plan step test-first "
       "inside its files_touched and writes a short log. " + ONLY.format(skill="karagoz"))
      for e in ("low", "medium", "high")],
    *[(f"worker-opus-{e}", "worker", "opus", e, "deny",
       f"Karagöz refactor-round Worker (Opus, {e} effort): redoes one plan step that "
       "failed its audit, test-first, inside its files_touched. " + ONLY.format(skill="karagoz"))
      for e in ("high", "xhigh")],
    *[(f"observer-{e}", "observer", "opus", e, "deny",
       f"Karagöz Observer at {e} effort: adversarially audits one finished plan "
       "step by running its checks itself, and returns PASS or FAIL with evidence. "
       + ONLY.format(skill="karagoz"))
      for e in ("medium", "high")],
    ("critic", "critic", "opus", "medium", "Read, Glob, Grep",
     "Hacivat plan critic: reviews a plan on disk through one named lens and "
     "returns severity-tagged objections plus a 0-10 score. " + ONLY.format(skill="hacivat")),
]


def render(name, src, model, effort, tools, description):
    body = (SRC / f"{src}.md").read_text(encoding="utf-8")
    # json.dumps gives a double-quoted YAML scalar: descriptions contain ": ",
    # which strict YAML parsers (GitHub's renderer among them) reject unquoted.
    return (f"---\nname: {name}\ndescription: {json.dumps(description, ensure_ascii=False)}\n"
            f"model: {model}\neffort: {effort}\n"
            + (f"disallowedTools: {DENY}\n" if tools == "deny" else f"tools: {tools}\n")
            + "---\n\n"
            "<!-- Generated by tools/build_agents.py from tools/agents-src/"
            f"{src}.md — edit the source, not this file. -->\n\n{body}")


def main():
    check = "--check" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    wanted = {f"{v[0]}.md": render(*v) for v in VARIANTS}
    stale = [n for n, text in wanted.items()
             if not (OUT / n).exists() or (OUT / n).read_text(encoding="utf-8") != text]
    extra = [p.name for p in OUT.glob("*.md") if p.name not in wanted]
    if check:
        for n in stale + extra:
            print(f"stale: agents/{n}")
        sys.exit(1 if stale or extra else 0)
    for n in stale:
        (OUT / n).write_text(wanted[n], encoding="utf-8")
    for n in extra:
        (OUT / n).unlink()
    print(f"agents: {len(wanted)} ({len(stale)} written, {len(extra)} removed)")


if __name__ == "__main__":
    main()
